<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="robot_parameters.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- Materials -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="orange">
        <color rgba="1 0.5 0 1"/>
    </material>
    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <!-- Base link -->

    <link name="base_link">

    </link>
    <!-- Chassis frame -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.075 0 0" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <!-- Box origin at the back of AGV -->
            <origin xyz="${chassis_L/2} 0 ${chassis_H/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_L} ${chassis_W} ${chassis_H}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_L/2} 0 ${chassis_H/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_L} ${chassis_W} ${chassis_H}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_L}" y="${chassis_W}" z="${chassis_H}">
            <origin xyz="${chassis_L/2} 0 ${chassis_H/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>


    <!-- Left wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${chassis_W/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- Right wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${chassis_W/2 + wheel_width/2} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Caster wheel -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <!-- z = -wheel_radius + caster_radius = -0.037 + 0.02 = -0.017 -->
        <origin xyz="0.2 0 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${caster_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>
